title: Dev's Insights
email: oumaima.zerouali@gmail.com
description: >
  Dev's Insights is a blog where I share my thoughts, tutorials, and insights
  on programming, best practices, and the latest trends in
  technology. Join me as I explore new ideas and share some knowledge.
baseurl: "/devs-insights"
url: "https://oumaimazerouali.github.io"

theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-toc
  - jekyll-paginate

paginate: 5
paginate_path: "/page:num/"

linkedin_username: oumaima-zerouali-16b189223
github_username: OumaimaZerouali
instagram_username: zugzwang_o7

exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
