title: Dev's Insights
email: oumaima.zerouali@gmail.com
description: >
  A blog about tech and software development.
baseurl: "/devs-insights"
url: "https://oumaimazerouali.github.io"
metadata:
  author: Oumaima Zerouali
  keywords: Oumaima,Blog,Java,JavaScript,TypeScript,Angular,DevOps,Cloud,devsinights

theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-toc
  - jekyll-paginate
  - jekyll-seo-tag

paginate: 5
paginate_path: "/page:num/"

linkedin_username: oumaima-zerouali-16b189223
github_username: OumaimaZerouali
instagram_username: zugzwang_o7

seo:
  title: "Dev's Insight"
  description: "A blog about tech and software development."
  url: "https://oumaimazerouali.github.io/devs-insights/"

exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
